//Authentication
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const INVALID_USER = 'INVALID_USER';
export const UNAUTHORIZED_USER = 'UNAUTHORIZED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTHENTICATION_INPROGRESS = 'AUTHENTICATION_INPROGRESS';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_INPROGRESS = 'PASSWORD_CHANGE_INPROGRESS';
export const PASSWORD_CHANGE_NOT_SUCCESS = 'PASSWORD_CHANGE_NOT_SUCCESS';
export const PASSWORD_CONNECTION_ERROR = 'PASSWORD_CONNECTION_ERROR';
export const REGISTRATION_INPROGRESS = 'REGISTRATION_INPROGRESS';
export const REGISTRATION_NOT_SUCCESS = 'REGISTRATION_NOT_SUCCESS';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const USERPROFILE_DEFAULT_CLEAR = 'USERPROFILE_DEFAULT_CLEAR';


export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const FORGOT_PASSWORD_COMPLETE = 'FORGOT_PASSWORD_COMPLETE';
export const CHECK_FORGOT_PASSWORD_SUCCESS = 'CHECK_FORGOT_PASSWORD_SUCCESS';
export const CHECK_FORGOT_PASSWORD_ERROR = 'CHECK_FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';


//ManageUser
export const USER_INPROGRESS = 'USER_INPROGRESS';
export const USER_CONNECTION_ERROR = 'USER_CONNECTION_ERROR';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_CHANGE_NOT_SUCCESS = 'USER_CHANGE_NOT_SUCCESS';
export const USER_BLOCK_SUCCESS = 'USER_BLOCK_SUCCESS';
export const USER_BLOCK_NOT_SUCCESS = 'USER_BLOCK_NOT_SUCCESS';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_NOT_SUCCESS = 'USER_DELETE_NOT_SUCCESS';
export const USER_DEFAULT_CLEAR = 'USER_DEFAULT_CLEAR';

//ServiceManage
export const SERVICE_INPROGRESS = 'SERVICE_INPROGRESS';
export const SERVICE_CONNECTION_ERROR = 'SERVICE_CONNECTION_ERROR';
export const SERVICE_SUCCESS = 'SERVICE_SUCCESS';
export const SERVICE_DELETE_SUCCESS = 'SERVICE_DELETE_SUCCESS';
export const SERVICE_ADD_SUCCESS = 'SERVICE_ADD_SUCCESS';
export const SERVICE_EDIT_SUCCESS = 'SERVICE_EDIT_SUCCESS';
export const SERVICE_NOT_SUCCESS = 'SERVICE_NOT_SUCCESS';
export const SERVICE_DEFAULT_CLEAR = 'SERVICE_DEFAULT_CLEAR';

//TeamProductManage
export const PRODUCT_INPROGRESS = 'PRODUCT_INPROGRESS';
export const PRODUCT_CONNECTION_ERROR = 'PRODUCT_CONNECTION_ERROR';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const TEAM_MEMBER_PRODUCT_SUCCESS = 'TEAM_MEMBER_PRODUCT_SUCCESS';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_NOT_SUCCESS = 'PRODUCT_NOT_SUCCESS';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DEFAULT_CLEAR = 'PRODUCT_DEFAULT_CLEAR';

//SliderManage
export const SLIDER_INPROGRESS = 'SLIDER_INPROGRESS';
export const SLIDER_CONNECTION_ERROR = 'SLIDER_CONNECTION_ERROR';
export const SLIDER_SUCCESS = 'SLIDER_SUCCESS';
export const SLIDER_DELETE_SUCCESS = 'SLIDER_DELETE_SUCCESS';
export const SLIDER_ADD_SUCCESS = 'SLIDER_ADD_SUCCESS';
export const SLIDER_NOT_SUCCESS = 'SLIDER_NOT_SUCCESS';
export const SLIDER_DEFAULT_CLEAR = 'SLIDER_DEFAULT_CLEAR';


//GalleryManage
export const GALLERY_INPROGRESS = 'GALLERY_INPROGRESS';
export const GALLERY_CONNECTION_ERROR = 'GALLERY_CONNECTION_ERROR';
export const GALLERY_SUCCESS = 'GALLERY_SUCCESS';
export const GALLERY_DELETE_SUCCESS = 'GALLERY_DELETE_SUCCESS';
export const GALLERY_ADD_SUCCESS = 'GALLERY_ADD_SUCCESS';
export const GALLERY_EDIT_SUCCESS = 'GALLERY_EDIT_SUCCESS';
export const GALLERY_NOT_SUCCESS = 'GALLERY_NOT_SUCCESS';
export const GALLERY_DEFAULT_CLEAR = 'GALLERY_DEFAULT_CLEAR';


//TeamManage
export const TEAM_INPROGRESS = 'TEAM_INPROGRESS';
export const TEAM_CONNECTION_ERROR = 'TEAM_CONNECTION_ERROR';
export const TEAM_SUCCESS = 'TEAM_SUCCESS';
export const TEAM_DELETE_SUCCESS = 'TEAM_DELETE_SUCCESS';
export const TEAM_ADD_SUCCESS = 'TEAM_ADD_SUCCESS';
export const TEAM_EDIT_SUCCESS = 'TEAM_EDIT_SUCCESS';
export const TEAM_NOT_SUCCESS = 'TEAM_NOT_SUCCESS';
export const TEAM_DEFAULT_CLEAR = 'TEAM_DEFAULT_CLEAR';

//SOD
export const SOD_INPROGRESS = 'SOD_INPROGRESS';
export const SOD_CONNECTION_ERROR = 'SOD_CONNECTION_ERROR';
export const SOD_SUCCESS = 'SOD_SUCCESS';
export const SOD_NOT_SUCCESS = 'SOD_NOT_SUCCESS';
export const SOD_RUNNING_LATE_MOVE_TO_PROGRESS = 'SOD_RUNNING_LATE_MOVE_TO_PROGRESS';
export const SOD_RECENT_MOVE_TO_PROGRESS = 'SOD_RECENT_MOVE_TO_PROGRESS';
export const SOD_RECENT_NEW_ORDER = 'SOD_RECENT_NEW_ORDER';
export const SOD_MOVE_TO_RUNNING_LATE = 'SOD_MOVE_TO_RUNNING_LATE';
export const SOD_MOVE_TO_PROCESSS_SUCCESS = 'SOD_MOVE_TO_PROCESSS_SUCCESS';
export const SOD_RECENT_MOVE_TO_FINISH = 'SOD_RECENT_MOVE_TO_FINISH';
export const SOD_FINISH_MOVE_TO_PAYMENT_FINISH = 'SOD_FINISH_MOVE_TO_PAYMENT_FINISH';

//Website
export const WEBSITE_INPROGRESS = 'WEBSITE_INPROGRESS';
export const WEBSITE_NOT_SUCCESS = 'WEBSITE_NOT_SUCCESS';
export const WEBSITE_CONNECTION_ERROR = 'WEBSITE_CONNECTION_ERROR';
export const ALL_GALLERY_SUCCESS = 'ALL_GALLERY_SUCCESS';
export const WEBSITE_HOME = 'WEBSITE_HOME';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ADDPRODUCTTOCART = 'ADDPRODUCTTOCART';
export const REMOVEPRODUCTTOCART = 'REMOVEPRODUCTTOCART';
export const ALL_TIMESLOTS_SUCCESS = 'ALL_TIMESLOTS_SUCCESS';
export const ORDER_PLACE = 'ORDER_PLACE';
export const COMPLETED_ORDER_LIST = 'COMPLETED_ORDER_LIST';
export const BASKETVISIBLE = 'BASKETVISIBLE';

//Video
export const VIDEO_INPROGRESS = 'VIDEO_INPROGRESS';
export const VIDEO_CONNECTION_ERROR = 'VIDEO_CONNECTION_ERROR';
export const VIDEO_SUCCESS = 'VIDEO_SUCCESS';
export const VIDEO_DELETE_SUCCESS = 'VIDEO_DELETE_SUCCESS';
export const VIDEO_ADD_SUCCESS = 'VIDEO_ADD_SUCCESS';
export const VIDEO_EDIT_SUCCESS = 'VIDEO_EDIT_SUCCESS';
export const VIDEO_NOT_SUCCESS = 'VIDEO_NOT_SUCCESS';
export const VIDEO_DEFAULT_CLEAR = 'VIDEO_DEFAULT_CLEAR';

//TimeSlot
export const TIMESLOT_INPROGRESS = 'TIMESLOT_INPROGRESS';
export const TIMESLOT_CONNECTION_ERROR = 'TIMESLOT_CONNECTION_ERROR';
export const TIMESLOT_SUCCESS = 'TIMESLOT_SUCCESS';
export const TIMESLOT_DELETE_SUCCESS = 'TIMESLOT_DELETE_SUCCESS';
export const TIMESLOT_ADD_SUCCESS = 'TIMESLOT_ADD_SUCCESS';
export const TIMESLOT_EDIT_SUCCESS = 'TIMESLOT_EDIT_SUCCESS';
export const TIMESLOT_NOT_SUCCESS = 'TIMESLOT_NOT_SUCCESS';
export const TIMESLOT_DEFAULT_CLEAR = 'TIMESLOT_DEFAULT_CLEAR';

//Analytics
export const ANALYTICS_INPROGRESS = 'ANALYTICS_INPROGRESS';
export const ANALYTICS_CONNECTION_ERROR = 'ANALYTICS_CONNECTION_ERROR';
export const ANALYTICS_SUCCESS = 'ANALYTICS_SUCCESS';
export const ANALYTICS_NOT_SUCCESS = 'ANALYTICS_NOT_SUCCESS';
export const ANALYTICS_DEFAULT_CLEAR = 'ANALYTICS_DEFAULT_CLEAR';
