const ENVIRONMENT_DEVELOPMENT = {
    API_URL: "APIURL",
    PHOTO_URL: "APIURL",
    SOCKET_URL: "APIURL",
    PRODUCT_IMAGE: "APIURL"
};

const ENVIRONMENT_PRODUCTION = {
    API_URL: "APIURL",
    PHOTO_URL: "APIURL",
    SOCKET_URL: "APIURL",
    PRODUCT_IMAGE: "APIURL"
};

let ENVIRONMENT_VARIABLES;

if (process.env.NODE_ENV === "development") {
    ENVIRONMENT_VARIABLES = ENVIRONMENT_DEVELOPMENT;
} else {
    ENVIRONMENT_VARIABLES = ENVIRONMENT_PRODUCTION;
}

export default ENVIRONMENT_VARIABLES;
